### ISSUE TITLE
Setup example with sdk-java

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/cdk#11]
Setup example with sdk java and test it's correctly working with lambda.

**Comment by tillrohrmann** [comment]
@pcholakov has this been done?

**Comment by pcholakov** [comment]
Not quite but very close! PR incoming – I worked on it on Friday but never posted an update to the issue.

What's included:

- add a new `kotlin-cdk-lambda` example to https://github.com/restatedev/examples
- trivial hello-world code
- based on the CDK code in https://github.com/restatedev/restate-holiday but without the self-hosted Restate+EC2 stack

**Comment by tillrohrmann** [comment]
Thanks for the update @pcholakov.

**Comment by pcholakov** [comment]
https://github.com/restatedev/examples/pull/50 - @slinkydeveloper thanks for the feedback!

**Comment by pcholakov** [comment]
https://github.com/restatedev/examples/pull/50 is just missing the update to the final artifact versions from the public maven repo but is otherwise ready for review.
