### ISSUE TITLE
Expand the README to include some pointers on getting started with CDK

### ISSUE THREAD

**Issue by pcholakov** [restatedev/cdk#18]
The information published at https://www.npmjs.com/package/@restatedev/restate-cdk is very sparse; it should contain some pointers on getting started with the CDK and probably a link to https://github.com/restatedev/examples/pull/50 once merged.

**Comment by pcholakov** [comment]
PR: https://github.com/restatedev/cdk/pull/20

**Comment by pcholakov** [comment]
Also added a new page to the doc website: https://github.com/restatedev/documentation/pull/234

**Comment by pcholakov** [comment]
Merged but won't release a new npm artifact until we have released the documentation (which is in turned blocked on releasing the runtime with the latest interface changes).

**Comment by tillrohrmann** [comment]
Why is the CDK release blocked on the documentation release @pcholakov?

**Comment by pcholakov** [comment]
The updated README links to the as-yet-unpublished CDK page introduced by https://github.com/restatedev/documentation/pull/234 – do you think it's enough of an improvement to release even with a broken link?

**Comment by tillrohrmann** [comment]
The broken link is not perfect but strictly speaking it already exists when looking at the README in main of this repo. Given that the README already contains a lot of helpful information compared to the is-state, I would be fine with creating a release with a temporarily broken link.

**Comment by pcholakov** [comment]
You are quite right! I just had a mental block against pushing out the broken link – this is still a strict improvement.

v0.4.2 release kicked off: https://github.com/restatedev/cdk/actions/runs/7388711431

**Comment by pcholakov** [comment]
Much better! https://www.npmjs.com/package/@restatedev/restate-cdk

**Comment by tillrohrmann** [comment]
> Much better! https://www.npmjs.com/package/@restatedev/restate-cdk

Cool :-)
